"""Arma CobroFacil_POS.exe. Lo usa GitHub Actions y el compilador local.

Una librería nueva va en requirements.txt. El release hace pip install -r
requirements.txt y después corre este archivo. Si el import no está acá,
el ejecutable del cliente abre el módulo y se cierra.
"""
from __future__ import annotations

import subprocess
import sys
from pathlib import Path

RAIZ = Path(__file__).resolve().parents[1]

OBLIGATORIOS = (
    "reportlab",
    "barcode",
    "qrcode",
    "PyQt6.QtPrintSupport",
    "sqlalchemy",
    "bcrypt",
)


def exigir_librerias() -> None:
    faltan = []
    for nombre in OBLIGATORIOS:
        try:
            __import__(nombre)
        except Exception as exc:
            faltan.append(f"{nombre}: {exc}")
    if faltan:
        raise SystemExit(
            "Faltan librerías del ejecutable. Están en requirements.txt:\n"
            + "\n".join(faltan)
        )


def argumentos() -> list[str]:
    return [
        "--noconfirm",
        "--onedir",
        "--windowed",
        "--name",
        "CobroFacil_POS",
        "--exclude-module",
        "PyQt5",
        "--exclude-module",
        "tkinter",
        "--exclude-module",
        "tcl",
        "--exclude-module",
        "_tkinter",
        "--exclude-module",
        "Tkinter",
        "--exclude-module",
        "rembg",
        "--exclude-module",
        "scipy",
        "--exclude-module",
        "src.carteleria.creador_png.convertir_imagen",
        "--hidden-import",
        "reportlab",
        "--collect-all",
        "reportlab",
        "--hidden-import",
        "barcode",
        "--collect-all",
        "barcode",
        "--hidden-import",
        "qrcode",
        "--collect-all",
        "qrcode",
        "--hidden-import",
        "sqlalchemy",
        "--hidden-import",
        "bcrypt",
        "--hidden-import",
        "PyQt6.QtPrintSupport",
        "--collect-all",
        "PyQt6.QtPrintSupport",
        "--hidden-import",
        "reportlab.graphics.barcode.code93",
        "--hidden-import",
        "reportlab.graphics.barcode.code128",
        "--hidden-import",
        "reportlab.graphics.barcode.code39",
        "--hidden-import",
        "reportlab.graphics.barcode.eanbc",
        "--hidden-import",
        "src.cajero.paso5_terminal.componentes_paso5_terminal.componentes_barra_inferior.chatbot.chat_bot",
        "--hidden-import",
        "src.cajero.paso5_terminal.componentes_paso5_terminal.barra_de_herramientas_inferior.chatbot",
        "--hidden-import",
        "src.cajero.paso5_terminal.componentes_paso5_terminal.barra_de_herramientas_inferior.chatbot.boton",
        "--hidden-import",
        "lxml",
        "--hidden-import",
        "html5lib",
        "--hidden-import",
        "openpyxl",
        "--hidden-import",
        "win32com",
        "--hidden-import",
        "win32com.client",
        "--hidden-import",
        "PyQt6.QtWebEngineWidgets",
        "--hidden-import",
        "PyQt6.QtWebEngineCore",
        "--collect-all",
        "PyQt6.QtWebEngineCore",
        "--collect-all",
        "PyQt6.QtWebEngineWidgets",
        "--collect-submodules",
        "src.admin",
        "--collect-submodules",
        "src.jefe",
        "--collect-submodules",
        "src.cajero",
        "--hidden-import",
        "src.cajero.paso6_cobro.transferencia_en_cobro.panel",
        "--hidden-import",
        "src.cajero.paso6_cobro.transferencia_en_cobro.cuenta",
        "--hidden-import",
        "src.cajero.paso6_cobro.aviso_en_cobro.toast",
        "--hidden-import",
        "src.cajero.paso6_cobro.tarjeta_en_cobro.panel",
        "--hidden-import",
        "src.cajero.paso6_cobro.tarjeta_en_cobro.envio",
        "--hidden-import",
        "src.cajero.paso6_cobro.qr_en_cobro.panel",
        "--hidden-import",
        "src.cajero.paso6_cobro.mixto_en_cobro.panel",
        "--hidden-import",
        "src.cajero.paso6_cobro.mixto_en_cobro.confirmar",
        "--hidden-import",
        "src.cajero.paso6_cobro.monto_en_cobro.panel",
        "--hidden-import",
        "src.admin.mercadopago.historial.archivo",
        "--hidden-import",
        "src.admin.mercadopago.historial.sincronizar",
        "--hidden-import",
        "src.services.mp_escucha",
        "--hidden-import",
        "src.cajero.paso6_cobro.vinculo_mp.libro",
        "--hidden-import",
        "src.cajero.paso6_cobro.qr_en_cobro.pedido",
        "--hidden-import",
        "src.cajero.paso6_cobro.mercadopago_core.api_client",
        "--hidden-import",
        "src.cajero.paso6_cobro.mercadopago_core.point_service",
        "--hidden-import",
        "src.cajero.paso6_cobro.mercadopago_core.polling_service",
        "--hidden-import",
        "src.cajero.paso6_cobro.mercadopago_core.ui_dialogs",
        "--hidden-import",
        "src.utils.dinero",
        "--hidden-import",
        "src.admin.mercadopago.mercadopago_main",
        "--hidden-import",
        "src.admin.mercadopago.componentes.mp_polling_thread",
        "--collect-submodules",
        "src.carteleria",
        "--collect-submodules",
        "src.motor_descuentos",
        "--hidden-import",
        "src.motor_descuentos.vistas.dialog_gestor_publicidad",
        "--hidden-import",
        "src.motor_descuentos.vistas.ofertas_main",
        "--hidden-import",
        "src.carteleria.creador_png.app",
        "--hidden-import",
        "src.carteleria.creador_png.servidor",
        "--hidden-import",
        "flask",
        "--hidden-import",
        "jinja2",
        "--hidden-import",
        "werkzeug",
        "--copy-metadata",
        "werkzeug",
        "--copy-metadata",
        "flask",
        "--copy-metadata",
        "jinja2",
        "--copy-metadata",
        "markupsafe",
        "--copy-metadata",
        "itsdangerous",
        "--copy-metadata",
        "blinker",
        "--copy-metadata",
        "click",
        "--collect-all",
        "flask",
        "--collect-all",
        "werkzeug",
        "--runtime-hook",
        "01_Compiladores_y_Ejecutables/rthooks/pyi_rth_qt_dll_path.py",
        "--runtime-hook",
        "01_Compiladores_y_Ejecutables/rthooks/pyi_rth_pkg_metadata.py",
        "--collect-submodules",
        "src.services",
        "--collect-submodules",
        "src.utils",
        "--collect-submodules",
        "src.base_de_datos",
        "--collect-submodules",
        "src.inicio_y_perfiles",
        "--collect-submodules",
        "src.central_red_global",
        "--collect-submodules",
        "src.ui_global",
        "--add-data",
        "src/ui_components;src/ui_components",
        "--add-data",
        "src/cajero/paso5_terminal/componentes_paso5_terminal/apariencia;src/cajero/paso5_terminal/componentes_paso5_terminal/apariencia",
        "--add-data",
        "src/assets;src/assets",
        "--add-data",
        "src/carteleria/assets;src/carteleria/assets",
        "--add-data",
        "build/tv_cara.bin;.",
        "--add-data",
        "src/carteleria/lanzador_tv/la_cara_web;src/carteleria/lanzador_tv/la_cara_web",
        "--add-data",
        "src/carteleria/creador_png/templates;src/carteleria/creador_png/templates",
        "--add-data",
        "src/carteleria/creador_png/static;src/carteleria/creador_png/static",
        "--add-data",
        "Catalogos;Catalogos",
        "main.py",
    ]


def main() -> None:
    exigir_librerias()
    cmd = [sys.executable, "-m", "PyInstaller", *argumentos()]
    raise SystemExit(subprocess.call(cmd, cwd=str(RAIZ)))


if __name__ == "__main__":
    main()
