"""Presets del Creador PNG. Un clic aplica todo; sin barras de ajustes."""

PRESETS = {
    "carteleria": {
        "black_threshold": 50,
        "white_threshold": 220,
        "sharpness_factor": 1.4,
        "contrast_factor": 1.15,
        "saturation_factor": 1.2,
        "brightness_factor": 1.05,
        "output_size": "1024",
        "output_folder": "carteleria",
        "temperature": 0.4,
        "wet_shine_intensity": 0.15,
        "water_droplets_density": 0,
        "enable_depth_effect": True,
        "enable_vignette_effect": False,
        "enable_rim_light_effect": True,
    },
    "fresco": {
        "black_threshold": 50,
        "white_threshold": 220,
        "sharpness_factor": 1.4,
        "contrast_factor": 1.15,
        "saturation_factor": 1.1,
        "brightness_factor": 1.05,
        "output_size": "1024",
        "output_folder": "carteleria",
        "temperature": -0.3,
        "wet_shine_intensity": 0.1,
        "water_droplets_density": 0,
        "enable_depth_effect": True,
        "enable_vignette_effect": False,
        "enable_rim_light_effect": True,
    },
    "intenso": {
        "black_threshold": 50,
        "white_threshold": 220,
        "sharpness_factor": 1.5,
        "contrast_factor": 1.3,
        "saturation_factor": 1.4,
        "brightness_factor": 1.0,
        "output_size": "1024",
        "output_folder": "carteleria",
        "temperature": 0.2,
        "wet_shine_intensity": 0.2,
        "water_droplets_density": 0,
        "enable_depth_effect": True,
        "enable_vignette_effect": True,
        "enable_rim_light_effect": True,
    },
    "cromo": {
        "black_threshold": 50,
        "white_threshold": 220,
        "sharpness_factor": 1.6,
        "contrast_factor": 1.4,
        "saturation_factor": 0.0,
        "brightness_factor": 1.1,
        "output_size": "1024",
        "output_folder": "carteleria",
        "temperature": 0,
        "wet_shine_intensity": 0.3,
        "water_droplets_density": 0,
        "enable_depth_effect": True,
        "enable_vignette_effect": False,
        "enable_rim_light_effect": True,
    },
    "frio_rocio": {
        "black_threshold": 50,
        "white_threshold": 220,
        "sharpness_factor": 1.4,
        "contrast_factor": 1.1,
        "saturation_factor": 1.05,
        "brightness_factor": 1.05,
        "output_size": "1024",
        "output_folder": "carteleria",
        "temperature": -0.7,
        "wet_shine_intensity": 0.22,
        "water_droplets_density": 28,
        "enable_depth_effect": False,
        "enable_vignette_effect": False,
        "enable_rim_light_effect": False,
    }
}
